using SDL2;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SDL2NETKeyboardSample
{
    /// <summary>
    /// Holds keyboard keycode mappings for SDL and Scorp/Mono key codes.
    /// </summary>
    public static class KeyboardKeyMapper
    {
        #region Private Vars
        /// <summary>
        /// Holds the mappings of SDL key codes to Scorp/Mono key codes.
        /// </summary>
        private static Dictionary<SDL.SDL_Keycode, InputKeys> _sdlToScorpMappings = new Dictionary<SDL.SDL_Keycode, InputKeys>()
        {
            { SDL.SDL_Keycode.SDLK_UNKNOWN, InputKeys.None },
            { SDL.SDL_Keycode.SDLK_BACKSPACE, InputKeys.Back },
            { SDL.SDL_Keycode.SDLK_TAB, InputKeys.Tab },
            { SDL.SDL_Keycode.SDLK_RETURN, InputKeys.Enter },
            { SDL.SDL_Keycode.SDLK_ESCAPE, InputKeys.Escape },
            { SDL.SDL_Keycode.SDLK_SPACE, InputKeys.Space },
            { SDL.SDL_Keycode.SDLK_QUOTE, InputKeys.OemQuotes },
            { SDL.SDL_Keycode.SDLK_COMMA, InputKeys.OemComma },
            { SDL.SDL_Keycode.SDLK_MINUS, InputKeys.OemMinus },
            { SDL.SDL_Keycode.SDLK_PERIOD, InputKeys.OemPeriod },
            { SDL.SDL_Keycode.SDLK_SLASH, InputKeys.OemQuestion },
            { SDL.SDL_Keycode.SDLK_0, InputKeys.D0 },
            { SDL.SDL_Keycode.SDLK_1, InputKeys.D1 },
            { SDL.SDL_Keycode.SDLK_2, InputKeys.D2 },
            { SDL.SDL_Keycode.SDLK_3, InputKeys.D3 },
            { SDL.SDL_Keycode.SDLK_4, InputKeys.D4 },
            { SDL.SDL_Keycode.SDLK_5, InputKeys.D5 },
            { SDL.SDL_Keycode.SDLK_6, InputKeys.D6 },
            { SDL.SDL_Keycode.SDLK_7, InputKeys.D7 },
            { SDL.SDL_Keycode.SDLK_8, InputKeys.D8 },
            { SDL.SDL_Keycode.SDLK_9, InputKeys.D9 },
            { SDL.SDL_Keycode.SDLK_SEMICOLON, InputKeys.OemSemicolon },
            { SDL.SDL_Keycode.SDLK_EQUALS, InputKeys.OemPlus },
            { SDL.SDL_Keycode.SDLK_LEFTBRACKET, InputKeys.OemOpenBrackets },
            { SDL.SDL_Keycode.SDLK_BACKSLASH, InputKeys.OemPipe },
            { SDL.SDL_Keycode.SDLK_RIGHTBRACKET, InputKeys.OemCloseBrackets },
            { SDL.SDL_Keycode.SDLK_BACKQUOTE, InputKeys.OemTilde },
            { SDL.SDL_Keycode.SDLK_a, InputKeys.A },
            { SDL.SDL_Keycode.SDLK_b, InputKeys.B },
            { SDL.SDL_Keycode.SDLK_c, InputKeys.C },
            { SDL.SDL_Keycode.SDLK_d, InputKeys.D },
            { SDL.SDL_Keycode.SDLK_e, InputKeys.E },
            { SDL.SDL_Keycode.SDLK_f, InputKeys.F },
            { SDL.SDL_Keycode.SDLK_g, InputKeys.G },
            { SDL.SDL_Keycode.SDLK_h, InputKeys.H },
            { SDL.SDL_Keycode.SDLK_i, InputKeys.I },
            { SDL.SDL_Keycode.SDLK_j, InputKeys.J },
            { SDL.SDL_Keycode.SDLK_k, InputKeys.K },
            { SDL.SDL_Keycode.SDLK_l, InputKeys.L },
            { SDL.SDL_Keycode.SDLK_m, InputKeys.M },
            { SDL.SDL_Keycode.SDLK_n, InputKeys.N },
            { SDL.SDL_Keycode.SDLK_o, InputKeys.O },
            { SDL.SDL_Keycode.SDLK_p, InputKeys.P },
            { SDL.SDL_Keycode.SDLK_q, InputKeys.Q },
            { SDL.SDL_Keycode.SDLK_r, InputKeys.R },
            { SDL.SDL_Keycode.SDLK_s, InputKeys.S },
            { SDL.SDL_Keycode.SDLK_t, InputKeys.T },
            { SDL.SDL_Keycode.SDLK_u, InputKeys.U },
            { SDL.SDL_Keycode.SDLK_v, InputKeys.V },
            { SDL.SDL_Keycode.SDLK_w, InputKeys.W },
            { SDL.SDL_Keycode.SDLK_x, InputKeys.X },
            { SDL.SDL_Keycode.SDLK_y, InputKeys.Y },
            { SDL.SDL_Keycode.SDLK_z, InputKeys.Z },
            { SDL.SDL_Keycode.SDLK_DELETE, InputKeys.Delete },
            { SDL.SDL_Keycode.SDLK_CAPSLOCK, InputKeys.CapsLock },
            { SDL.SDL_Keycode.SDLK_F1, InputKeys.F1 },
            { SDL.SDL_Keycode.SDLK_F2, InputKeys.F2 },
            { SDL.SDL_Keycode.SDLK_F3, InputKeys.F3 },
            { SDL.SDL_Keycode.SDLK_F4, InputKeys.F4 },
            { SDL.SDL_Keycode.SDLK_F5, InputKeys.F5 },
            { SDL.SDL_Keycode.SDLK_F6, InputKeys.F6 },
            { SDL.SDL_Keycode.SDLK_F7, InputKeys.F7 },
            { SDL.SDL_Keycode.SDLK_F8, InputKeys.F8 },
            { SDL.SDL_Keycode.SDLK_F9, InputKeys.F9 },
            { SDL.SDL_Keycode.SDLK_F10, InputKeys.F10 },
            { SDL.SDL_Keycode.SDLK_F11, InputKeys.F11 },
            { SDL.SDL_Keycode.SDLK_F12, InputKeys.F12 },
            { SDL.SDL_Keycode.SDLK_SCROLLLOCK, InputKeys.Scroll },
            { SDL.SDL_Keycode.SDLK_PAUSE, InputKeys.Pause },
            { SDL.SDL_Keycode.SDLK_INSERT, InputKeys.Insert },
            { SDL.SDL_Keycode.SDLK_HOME, InputKeys.Home },
            { SDL.SDL_Keycode.SDLK_PAGEUP, InputKeys.PageUp },
            { SDL.SDL_Keycode.SDLK_END, InputKeys.End },
            { SDL.SDL_Keycode.SDLK_PAGEDOWN, InputKeys.PageDown },
            { SDL.SDL_Keycode.SDLK_RIGHT, InputKeys.Right },
            { SDL.SDL_Keycode.SDLK_LEFT, InputKeys.Left },
            { SDL.SDL_Keycode.SDLK_DOWN, InputKeys.Down },
            { SDL.SDL_Keycode.SDLK_UP, InputKeys.Up },
            { SDL.SDL_Keycode.SDLK_NUMLOCKCLEAR, InputKeys.NumLock },
            { SDL.SDL_Keycode.SDLK_KP_DIVIDE, InputKeys.Divide },
            { SDL.SDL_Keycode.SDLK_KP_MULTIPLY, InputKeys.Multiply },
            { SDL.SDL_Keycode.SDLK_KP_MINUS, InputKeys.Subtract },
            { SDL.SDL_Keycode.SDLK_KP_PLUS, InputKeys.Add },
            { SDL.SDL_Keycode.SDLK_KP_ENTER, InputKeys.Enter },
            { SDL.SDL_Keycode.SDLK_KP_1, InputKeys.NumPad1 },
            { SDL.SDL_Keycode.SDLK_KP_2, InputKeys.NumPad2 },
            { SDL.SDL_Keycode.SDLK_KP_3, InputKeys.NumPad3 },
            { SDL.SDL_Keycode.SDLK_KP_4, InputKeys.NumPad4 },
            { SDL.SDL_Keycode.SDLK_KP_5, InputKeys.NumPad5 },
            { SDL.SDL_Keycode.SDLK_KP_6, InputKeys.NumPad6 },
            { SDL.SDL_Keycode.SDLK_KP_7, InputKeys.NumPad7 },
            { SDL.SDL_Keycode.SDLK_KP_8, InputKeys.NumPad8 },
            { SDL.SDL_Keycode.SDLK_KP_9, InputKeys.NumPad9 },
            { SDL.SDL_Keycode.SDLK_KP_0, InputKeys.NumPad0 },
            { SDL.SDL_Keycode.SDLK_KP_PERIOD, InputKeys.Decimal },
            { SDL.SDL_Keycode.SDLK_APPLICATION, InputKeys.Apps },
            { SDL.SDL_Keycode.SDLK_F13, InputKeys.F13 },
            { SDL.SDL_Keycode.SDLK_F14, InputKeys.F14 },
            { SDL.SDL_Keycode.SDLK_F15, InputKeys.F15 },
            { SDL.SDL_Keycode.SDLK_F16, InputKeys.F16 },
            { SDL.SDL_Keycode.SDLK_F17, InputKeys.F17 },
            { SDL.SDL_Keycode.SDLK_F18, InputKeys.F18 },
            { SDL.SDL_Keycode.SDLK_F19, InputKeys.F19 },
            { SDL.SDL_Keycode.SDLK_F20, InputKeys.F20 },
            { SDL.SDL_Keycode.SDLK_F21, InputKeys.F21 },
            { SDL.SDL_Keycode.SDLK_F22, InputKeys.F22 },
            { SDL.SDL_Keycode.SDLK_F23, InputKeys.F23 },
            { SDL.SDL_Keycode.SDLK_F24, InputKeys.F24 },
            { SDL.SDL_Keycode.SDLK_EXECUTE, InputKeys.Execute },
            { SDL.SDL_Keycode.SDLK_HELP, InputKeys.Help },
            { SDL.SDL_Keycode.SDLK_SELECT, InputKeys.Select },
            { SDL.SDL_Keycode.SDLK_MUTE, InputKeys.VolumeMute },
            { SDL.SDL_Keycode.SDLK_VOLUMEUP, InputKeys.VolumeUp },
            { SDL.SDL_Keycode.SDLK_VOLUMEDOWN, InputKeys.VolumeDown },
            { SDL.SDL_Keycode.SDLK_SEPARATOR, InputKeys.Separator },
            { SDL.SDL_Keycode.SDLK_CRSEL, InputKeys.Crsel },
            { SDL.SDL_Keycode.SDLK_EXSEL, InputKeys.Exsel },
            { SDL.SDL_Keycode.SDLK_LCTRL, InputKeys.LeftControl },
            { SDL.SDL_Keycode.SDLK_LSHIFT, InputKeys.LeftShift },
            { SDL.SDL_Keycode.SDLK_LALT, InputKeys.LeftAlt },
            { SDL.SDL_Keycode.SDLK_LGUI, InputKeys.LeftWindows },
            { SDL.SDL_Keycode.SDLK_RCTRL, InputKeys.RightControl },
            { SDL.SDL_Keycode.SDLK_RSHIFT, InputKeys.RightShift },
            { SDL.SDL_Keycode.SDLK_RALT, InputKeys.RightAlt },
            { SDL.SDL_Keycode.SDLK_RGUI, InputKeys.RightWindows },
            { SDL.SDL_Keycode.SDLK_AUDIONEXT, InputKeys.MediaNextTrack },
            { SDL.SDL_Keycode.SDLK_AUDIOPREV, InputKeys.MediaPreviousTrack },
            { SDL.SDL_Keycode.SDLK_AUDIOSTOP, InputKeys.MediaStop },
            { SDL.SDL_Keycode.SDLK_AUDIOPLAY, InputKeys.MediaPlayPause },
            { SDL.SDL_Keycode.SDLK_AUDIOMUTE, InputKeys.VolumeMute },
            { SDL.SDL_Keycode.SDLK_MEDIASELECT, InputKeys.SelectMedia },
            { SDL.SDL_Keycode.SDLK_MAIL, InputKeys.LaunchMail },
            { SDL.SDL_Keycode.SDLK_AC_SEARCH, InputKeys.BrowserSearch },
            { SDL.SDL_Keycode.SDLK_AC_HOME, InputKeys.BrowserHome },
            { SDL.SDL_Keycode.SDLK_AC_BACK, InputKeys.BrowserBack },
            { SDL.SDL_Keycode.SDLK_AC_FORWARD, InputKeys.BrowserForward },
            { SDL.SDL_Keycode.SDLK_AC_STOP, InputKeys.BrowserStop },
            { SDL.SDL_Keycode.SDLK_AC_REFRESH, InputKeys.BrowserRefresh },
            { SDL.SDL_Keycode.SDLK_AC_BOOKMARKS, InputKeys.BrowserFavorites }
        };

        /// <summary>
        /// Holds the mappings of Scorp/Mono key codes to SDL key codes.
        /// </summary>
        private static Dictionary<InputKeys, SDL.SDL_Keycode> _scorpToSDLMappings = new Dictionary<InputKeys, SDL.SDL_Keycode>()
        {
            { InputKeys.None, SDL.SDL_Keycode.SDLK_UNKNOWN },
            { InputKeys.Back, SDL.SDL_Keycode.SDLK_BACKSPACE },
            { InputKeys.Tab, SDL.SDL_Keycode.SDLK_TAB },
            { InputKeys.Enter, SDL.SDL_Keycode.SDLK_RETURN },
            { InputKeys.Escape, SDL.SDL_Keycode.SDLK_ESCAPE },
            { InputKeys.Space, SDL.SDL_Keycode.SDLK_SPACE },
            { InputKeys.OemQuotes, SDL.SDL_Keycode.SDLK_QUOTE },
            { InputKeys.OemComma, SDL.SDL_Keycode.SDLK_COMMA },
            { InputKeys.OemMinus, SDL.SDL_Keycode.SDLK_MINUS },
            { InputKeys.OemPeriod, SDL.SDL_Keycode.SDLK_PERIOD },
            { InputKeys.OemQuestion, SDL.SDL_Keycode.SDLK_SLASH },
            { InputKeys.D0, SDL.SDL_Keycode.SDLK_0 },
            { InputKeys.D1, SDL.SDL_Keycode.SDLK_1 },
            { InputKeys.D2, SDL.SDL_Keycode.SDLK_2 },
            { InputKeys.D3, SDL.SDL_Keycode.SDLK_3 },
            { InputKeys.D4, SDL.SDL_Keycode.SDLK_4 },
            { InputKeys.D5, SDL.SDL_Keycode.SDLK_5 },
            { InputKeys.D6, SDL.SDL_Keycode.SDLK_6 },
            { InputKeys.D7, SDL.SDL_Keycode.SDLK_7 },
            { InputKeys.D8, SDL.SDL_Keycode.SDLK_8 },
            { InputKeys.D9, SDL.SDL_Keycode.SDLK_9 },
            { InputKeys.OemSemicolon, SDL.SDL_Keycode.SDLK_SEMICOLON },
            { InputKeys.OemPlus, SDL.SDL_Keycode.SDLK_EQUALS },
            { InputKeys.OemOpenBrackets, SDL.SDL_Keycode.SDLK_LEFTBRACKET },
            { InputKeys.OemPipe, SDL.SDL_Keycode.SDLK_BACKSLASH },
            { InputKeys.OemCloseBrackets, SDL.SDL_Keycode.SDLK_RIGHTBRACKET },
            { InputKeys.OemTilde, SDL.SDL_Keycode.SDLK_BACKQUOTE },
            { InputKeys.A, SDL.SDL_Keycode.SDLK_a },
            { InputKeys.B, SDL.SDL_Keycode.SDLK_b },
            { InputKeys.C, SDL.SDL_Keycode.SDLK_c },
            { InputKeys.D, SDL.SDL_Keycode.SDLK_d },
            { InputKeys.E, SDL.SDL_Keycode.SDLK_e },
            { InputKeys.F, SDL.SDL_Keycode.SDLK_f },
            { InputKeys.G, SDL.SDL_Keycode.SDLK_g },
            { InputKeys.H, SDL.SDL_Keycode.SDLK_h },
            { InputKeys.I, SDL.SDL_Keycode.SDLK_i },
            { InputKeys.J, SDL.SDL_Keycode.SDLK_j },
            { InputKeys.K, SDL.SDL_Keycode.SDLK_k },
            { InputKeys.L, SDL.SDL_Keycode.SDLK_l },
            { InputKeys.M, SDL.SDL_Keycode.SDLK_m },
            { InputKeys.N, SDL.SDL_Keycode.SDLK_n },
            { InputKeys.O, SDL.SDL_Keycode.SDLK_o },
            { InputKeys.P, SDL.SDL_Keycode.SDLK_p },
            { InputKeys.Q, SDL.SDL_Keycode.SDLK_q },
            { InputKeys.R, SDL.SDL_Keycode.SDLK_r },
            { InputKeys.S, SDL.SDL_Keycode.SDLK_s },
            { InputKeys.T, SDL.SDL_Keycode.SDLK_t },
            { InputKeys.U, SDL.SDL_Keycode.SDLK_u },
            { InputKeys.V, SDL.SDL_Keycode.SDLK_v },
            { InputKeys.W, SDL.SDL_Keycode.SDLK_w },
            { InputKeys.X, SDL.SDL_Keycode.SDLK_x },
            { InputKeys.Y, SDL.SDL_Keycode.SDLK_y },
            { InputKeys.Z, SDL.SDL_Keycode.SDLK_z },
            { InputKeys.Delete, SDL.SDL_Keycode.SDLK_DELETE },
            { InputKeys.CapsLock, SDL.SDL_Keycode.SDLK_CAPSLOCK },
            { InputKeys.F1, SDL.SDL_Keycode.SDLK_F1 },
            { InputKeys.F2, SDL.SDL_Keycode.SDLK_F2 },
            { InputKeys.F3, SDL.SDL_Keycode.SDLK_F3 },
            { InputKeys.F4, SDL.SDL_Keycode.SDLK_F4 },
            { InputKeys.F5, SDL.SDL_Keycode.SDLK_F5 },
            { InputKeys.F6, SDL.SDL_Keycode.SDLK_F6 },
            { InputKeys.F7, SDL.SDL_Keycode.SDLK_F7 },
            { InputKeys.F8, SDL.SDL_Keycode.SDLK_F8 },
            { InputKeys.F9, SDL.SDL_Keycode.SDLK_F9 },
            { InputKeys.F10, SDL.SDL_Keycode.SDLK_F10 },
            { InputKeys.F11, SDL.SDL_Keycode.SDLK_F11 },
            { InputKeys.F12, SDL.SDL_Keycode.SDLK_F12 },
            { InputKeys.Scroll, SDL.SDL_Keycode.SDLK_SCROLLLOCK },
            { InputKeys.Pause, SDL.SDL_Keycode.SDLK_PAUSE },
            { InputKeys.Insert, SDL.SDL_Keycode.SDLK_INSERT },
            { InputKeys.Home, SDL.SDL_Keycode.SDLK_HOME },
            { InputKeys.PageUp, SDL.SDL_Keycode.SDLK_PAGEUP },
            { InputKeys.End, SDL.SDL_Keycode.SDLK_END },
            { InputKeys.PageDown, SDL.SDL_Keycode.SDLK_PAGEDOWN },
            { InputKeys.Right, SDL.SDL_Keycode.SDLK_RIGHT },
            { InputKeys.Left, SDL.SDL_Keycode.SDLK_LEFT },
            { InputKeys.Down, SDL.SDL_Keycode.SDLK_DOWN },
            { InputKeys.Up, SDL.SDL_Keycode.SDLK_UP },
            { InputKeys.NumLock, SDL.SDL_Keycode.SDLK_NUMLOCKCLEAR },
            { InputKeys.Divide, SDL.SDL_Keycode.SDLK_KP_DIVIDE },
            { InputKeys.Multiply, SDL.SDL_Keycode.SDLK_KP_MULTIPLY },
            { InputKeys.Subtract, SDL.SDL_Keycode.SDLK_KP_MINUS },
            { InputKeys.Add, SDL.SDL_Keycode.SDLK_KP_PLUS },
            { InputKeys.Enter, SDL.SDL_Keycode.SDLK_KP_ENTER },
            { InputKeys.NumPad1, SDL.SDL_Keycode.SDLK_KP_1 },
            { InputKeys.NumPad2, SDL.SDL_Keycode.SDLK_KP_2 },
            { InputKeys.NumPad3, SDL.SDL_Keycode.SDLK_KP_3 },
            { InputKeys.NumPad4, SDL.SDL_Keycode.SDLK_KP_4 },
            { InputKeys.NumPad5, SDL.SDL_Keycode.SDLK_KP_5 },
            { InputKeys.NumPad6, SDL.SDL_Keycode.SDLK_KP_6 },
            { InputKeys.NumPad7, SDL.SDL_Keycode.SDLK_KP_7 },
            { InputKeys.NumPad8, SDL.SDL_Keycode.SDLK_KP_8 },
            { InputKeys.NumPad9, SDL.SDL_Keycode.SDLK_KP_9 },
            { InputKeys.NumPad0, SDL.SDL_Keycode.SDLK_KP_0 },
            { InputKeys.Decimal, SDL.SDL_Keycode.SDLK_KP_PERIOD },
            { InputKeys.Apps, SDL.SDL_Keycode.SDLK_APPLICATION },
            { InputKeys.F13, SDL.SDL_Keycode.SDLK_F13 },
            { InputKeys.F14, SDL.SDL_Keycode.SDLK_F14 },
            { InputKeys.F15, SDL.SDL_Keycode.SDLK_F15 },
            { InputKeys.F16, SDL.SDL_Keycode.SDLK_F16 },
            { InputKeys.F17, SDL.SDL_Keycode.SDLK_F17 },
            { InputKeys.F18, SDL.SDL_Keycode.SDLK_F18 },
            { InputKeys.F19, SDL.SDL_Keycode.SDLK_F19 },
            { InputKeys.F20, SDL.SDL_Keycode.SDLK_F20 },
            { InputKeys.F21, SDL.SDL_Keycode.SDLK_F21 },
            { InputKeys.F22, SDL.SDL_Keycode.SDLK_F22 },
            { InputKeys.F23, SDL.SDL_Keycode.SDLK_F23 },
            { InputKeys.F24, SDL.SDL_Keycode.SDLK_F24 },
            { InputKeys.Execute, SDL.SDL_Keycode.SDLK_EXECUTE },
            { InputKeys.Help, SDL.SDL_Keycode.SDLK_HELP },
            { InputKeys.Select, SDL.SDL_Keycode.SDLK_SELECT },
            { InputKeys.VolumeMute, SDL.SDL_Keycode.SDLK_MUTE },
            { InputKeys.VolumeUp, SDL.SDL_Keycode.SDLK_VOLUMEUP },
            { InputKeys.VolumeDown, SDL.SDL_Keycode.SDLK_VOLUMEDOWN },
            { InputKeys.Separator, SDL.SDL_Keycode.SDLK_SEPARATOR },
            { InputKeys.Crsel, SDL.SDL_Keycode.SDLK_CRSEL },
            { InputKeys.Exsel, SDL.SDL_Keycode.SDLK_EXSEL },
            { InputKeys.LeftControl, SDL.SDL_Keycode.SDLK_LCTRL },
            { InputKeys.LeftShift, SDL.SDL_Keycode.SDLK_LSHIFT },
            { InputKeys.LeftAlt, SDL.SDL_Keycode.SDLK_LALT },
            { InputKeys.LeftWindows, SDL.SDL_Keycode.SDLK_LGUI },
            { InputKeys.RightControl, SDL.SDL_Keycode.SDLK_RCTRL },
            { InputKeys.RightShift, SDL.SDL_Keycode.SDLK_RSHIFT },
            { InputKeys.RightAlt, SDL.SDL_Keycode.SDLK_RALT },
            { InputKeys.RightWindows, SDL.SDL_Keycode.SDLK_RGUI },
            { InputKeys.MediaNextTrack, SDL.SDL_Keycode.SDLK_AUDIONEXT },
            { InputKeys.MediaPreviousTrack, SDL.SDL_Keycode.SDLK_AUDIOPREV },
            { InputKeys.MediaStop, SDL.SDL_Keycode.SDLK_AUDIOSTOP },
            { InputKeys.MediaPlayPause, SDL.SDL_Keycode.SDLK_AUDIOPLAY },
            { InputKeys.VolumeMute, SDL.SDL_Keycode.SDLK_AUDIOMUTE },
            { InputKeys.SelectMedia, SDL.SDL_Keycode.SDLK_MEDIASELECT },
            { InputKeys.LaunchMail, SDL.SDL_Keycode.SDLK_MAIL },
            { InputKeys.BrowserSearch, SDL.SDL_Keycode.SDLK_AC_SEARCH },
            { InputKeys.BrowserHome, SDL.SDL_Keycode.SDLK_AC_HOME },
            { InputKeys.BrowserBack, SDL.SDL_Keycode.SDLK_AC_BACK },
            { InputKeys.BrowserForward, SDL.SDL_Keycode.SDLK_AC_FORWARD },
            { InputKeys.BrowserStop, SDL.SDL_Keycode.SDLK_AC_STOP },
            { InputKeys.BrowserRefresh, SDL.SDL_Keycode.SDLK_AC_REFRESH },
            { InputKeys.BrowserFavorites, SDL.SDL_Keycode.SDLK_AC_BOOKMARKS }
        };
        #endregion


        #region Public Methods
        /// <summary>
        /// Converts the given <paramref name="key"/> of type <see cref="SDL.SDL_Keycode"/> to 
        /// the keycode of type <see cref="InputKeys"/>.
        /// </summary>
        /// <param name="key">The SDL key code used to map to the Scorp/Mono key code.</param>
        /// <returns></returns>
        public static InputKeys ToInputKey(SDL.SDL_Keycode key) => _sdlToScorpMappings[key];


        /// <summary>
        /// Converts the given <paramref name="key"/> of type <see cref="InputKeys"/> to
        /// the keycode of type <see cref="SDL.SDL_Keycode"/>.
        /// </summary>
        /// <param name="key">The Scorp/Mono key code used to map to the SDL key code.</param>
        /// <returns></returns>
        public static SDL.SDL_Keycode ToSDLKey(InputKeys key) => _scorpToSDLMappings[key];
        #endregion
    }
}
